#!/bin/bash
source library

clear
CurrentFolder=$(pwd)

cd maxscale
docker-compose down
cd ../galera
docker-compose down
cd ..

echo "y" | docker volume prune

cd galera
echo "Building MariaDB servers"

docker-compose up --detach --build
echo 
echo "Copying the config files for the cluster and server"
for i in 1 2 3
do
    for j in dc dr
    do
        strContainer=${j}g${i}
        verifyMariaDB ${strContainer}
        docker container exec ${strContainer} bash -c "mariadb -uroot < /tmp/init/01.sql"
        docker cp ./config/${j}-galera-${i}.cnf ${strContainer}:/etc/mysql/mariadb.conf.d/60-galera.cnf
        docker cp ./config/${j}-server-${i}.cnf ${strContainer}:/etc/mysql/mariadb.conf.d/50-server.cnf
    done
done
echo "."
echo "Set bootstrap for DC Node 1 and DR Node 1"
bootstrap dcg1
bootstrap drg1

echo "."
echo "Restarting Cluster one last time"
stopMriaDBCluster

echo "."
echo "Starting up Cluster with Galera configuration"

for i in 1 2 3
do
    for j in dc dr
    do
        strContainer=${j}g${i}
        serverStart ${strContainer}
    done
done
cd ..

# Create a testdb database to initiate 1st GTID
docker container exec dcg1 bash -c "mariadb -uroot < /tmp/init/02.sql"
docker container exec drg1 bash -c "mariadb -uroot < /tmp/init/02.sql"

#for i in 1 2 3
#do
#    for j in dc dr
#    do
#        strContainer=${j}g${i}
#        echo "Setting up GTID for ${strContainer}"
#        docker container exec ${strContainer} bash -c "mariadb -uroot < /tmp/init/${j}-gtid-setup.sql"
#    done
#done

echo "."
echo "Cluster restarted, setting up MaxScale"
cd maxscale
docker-compose up --detach --build
echo "MaxScale up and ready"
sleep 5
echo "."
exit 0
# Execute CHANGE MASTER for both sides to set up replication
echo "Setting up replication between dcg1 <-> drmxs & drg1 <-> dcmxs"
docker container exec dcg1 bash -c "mariadb -uroot < /tmp/init/dc-replication.sql"
docker container exec drg1 bash -c "mariadb -uroot < /tmp/init/dr-replication.sql"

dcStatus=$(docker container exec dcg1 bash -c "mariadb -uroot -e \"SHOW ALL SLAVES STATUS\G\"" | grep -i "running:")
drStatus=$(docker container exec drg1 bash -c "mariadb -uroot -e \"SHOW ALL SLAVES STATUS\G\"" | grep -i "running:")
echo 
echo "DC -> DR"
trim ${dcStatus}
echo
setupReady=0
if [ $(echo ${dcStatus} | grep -o "Yes" | wc -l) -eq 2 ]; then
    echo "Replciation DC to DR validated"
    ((setupReady=setupReady+1))
fi
echo
echo "DR -> DC"
trim ${drStatus}
echo
if [ $(echo ${drStatus} | grep -o "Yes" | wc -l) -eq 2 ]; then
    echo "Replciation DC to DR validated"
    ((setupReady=setupReady+1))
fi
echo 
if [[ ${setupReady} == 2 ]]; then
    echo "Clusters are ready..."
else
    echo "There were problems setting up the cluster"
    echo "Replication Failed"
fi
echo ""

cd ${CurrentFolder}