#!/bin/bash
source library

action=$1
containerName=$2

if [ ${action} == "stop" ]; then
    echo "Stopping node ${containerName}"
    docker container exec -it ${containerName} bash -c "mysqladmin -uroot --wait-for-all-slaves shutdown"
fi
if [ ${action} == "start" ]; then
    echo "Starting node ${containerName}"
    serverStart ${containerName}
fi
