#!/bin/bash
source library

# Execute CHANGE MASTER for both sides to set up replication
echo "Setting up replication between dcg1 <-> drmxs & drg1 <-> dcmxs"
docker container exec dcg1 bash -c "mariadb -uroot < /tmp/init/dc-replication.sql"
docker container exec drg1 bash -c "mariadb -uroot < /tmp/init/dr-replication.sql"

dcStatus=$(docker container exec dcg1 bash -c "mariadb -uroot -e \"SHOW ALL SLAVES STATUS\G\"" | grep -i "running:")
drStatus=$(docker container exec drg1 bash -c "mariadb -uroot -e \"SHOW ALL SLAVES STATUS\G\"" | grep -i "running:")
echo 
echo "DC -> DR"
trim ${dcStatus}
echo
setupReady=0
if [ $(echo ${dcStatus} | grep -o "Yes" | wc -l) -eq 2 ]; then
    echo "Replciation DC to DR validated"
    ((setupReady=setupReady+1))
fi
echo
echo "DR -> DC"
trim ${drStatus}
echo
if [ $(echo ${drStatus} | grep -o "Yes" | wc -l) -eq 2 ]; then
    echo "Replciation DC to DR validated"
    ((setupReady=setupReady+1))
fi
echo 
if [[ ${setupReady} == 2 ]]; then
    echo "Clusters are ready..."
else
    echo "There were problems setting up the cluster"
    echo "Replication Failed"
fi
echo ""

cd ${CurrentFolder}