#!/bin/bash
source library

echo "Shutting Down MaxScale!"
./maxsale/docker-compose restart
sleep 5
for i in 1 2 3
do
    for j in dc dr
    do
        strContainer=${j}g${i}
        echo "Stopping MariaDB process for node ${strContainer}"
        ./node stop ${j}g${i}
        serverStart ${j}g${i}

    done
done
