#!/bin/bash

echo "Shutting Down MaxScale!"
./maxsale/docker-compose stop
sleep 5
for i in 1 2 3
do
    for j in dc dr
    do
        echo "Stopping MariaDB process for node ${j}g${i}"
        docker container exec -it ${j}g${i} bash -c "mysqladmin --wait-for-all-slaves shutdown"
        sleep 3
    done
done
echo "Restarting Cluster!"
./galera/docker-compose restart
sleep 5
echo "Starting Up MaxScale!"
./maxsale/docker-compose start
