#!/bin/bash
source library

CurrentFolder=$(pwd)

cd maxscale
docker-compose start
sleep 5

cd ../galera

for i in 1 2 3
do
    for j in dc dr
    do
        echo "Starting MariaDB process for node ${j}g${i}"
        serverStart ${j}g${i}
    done
done

cd ${CurrentFolder}

