#!/bin/bash
CurrentFolder=$(pwd)

cd maxscale
docker-compose stop
cd ../galera

for i in 3 2 1
do
    for j in dc dr
    do
        strContainer=${j}g${i}
        ./node stop ${j} ${i}
    done
done

docker container exec dcg1 bash -c "touch /var/lib/mysql/bootstrap.ind"
docker container exec drg1 bash -c "touch /var/lib/mysql/bootstrap.ind"

cd ${CurrentFolder}

