#!/bin/bash
CurrentFolder=$(pwd)

cd maxscale
docker-compose stop
cd ../galera

for i in 1 2 3
do
    for j in dc dr
    do
        echo "Stopping MariaDB process for node ${j}g${i}"
        docker container exec -it ${j}g${i} bash -c "mysqladmin -uroot --wait-for-all-slaves shutdown"
    done
done

docker-compose stop
cd ${CurrentFolder}

